# Generated by Django 5.1.6 on 2025-05-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedResource',
        ),
    ]
