# Generated by Django 5.1.6 on 2025-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_delete_savedresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodinsight',
            name='stress_level',
            field=models.IntegerField(default=3),
        ),
    ]
