# Generated by Django 5.1.6 on 2025-05-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_moodinsight_stress_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content',
        ),
        migrations.AddField(
            model_name='report',
            name='recommedations',
            field=models.TextField(db_default='recommedations'),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(default='summary'),
        ),
    ]
