# Generated by Django 5.1.6 on 2025-05-02 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_report_content_report_recommedations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='recommedations',
        ),
        migrations.RemoveField(
            model_name='report',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='report',
            name='recommendations',
            field=models.TextField(default='recommendations'),
        ),
        migrations.AlterField(
            model_name='report',
            name='psychologist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
