# Generated by Django 5.1.6 on 2025-05-02 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_report_recommedations_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsedService',
        ),
    ]
