# Generated by Django 5.1.6 on 2025-05-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_delete_usedservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='rating',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='helpful',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='satisfaction',
            field=models.CharField(choices=[('Very Satisfied', 'Very Satisfied'), ('Satisfied', 'Satisfied'), ('Neutral', 'Neutral'), ('Dissatisfied', 'Dissatisfied'), ('Very Dissatisfied', 'Very Dissatisfied')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='suggestions',
            field=models.TextField(default='suggestions'),
        ),
    ]
