# Generated by Django 5.1.6 on 2025-05-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_userfeedback_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedback',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userfeedback',
            name='satisfaction',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='dashboard_feedback',
            field=models.CharField(choices=[('very_useful', 'Very Useful'), ('somewhat_useful', 'Somewhat Useful'), ('not_useful', 'Not Useful')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='ease_of_use',
            field=models.CharField(choices=[('very_easy', 'Very Easy'), ('easy', 'Easy'), ('average', 'Average'), ('difficult', 'Difficult')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='helpful',
            field=models.CharField(choices=[('yes', 'Yes'), ('somewhat', 'Somewhat'), ('no', 'No')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='suggestions',
            field=models.TextField(blank=True),
        ),
    ]
