# Generated by Django 5.1.6 on 2025-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_remove_userfeedback_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={},
        ),
        migrations.RenameField(
            model_name='userfeedback',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='recommend',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='satisfaction',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='dashboard_feedback',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='ease_of_use',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='helpful',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='suggestions',
            field=models.TextField(),
        ),
    ]
