# Generated by Django 5.1.6 on 2025-12-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_userfeedback_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('psychologist', 'Psychologist')], default='user', max_length=15),
        ),
    ]
