# Generated by Django 6.0 on 2026-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_customuser_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
